# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'default'

variables:
  fortifyDownloadUrl: 'https://fortifyfiler.fortifylab.net/Builds/SCA/25.4.0/25.4.0.0094/Windows/OpenText_SAST_Fortify_windows-x64_25.4.0.exe'
  fortifyInstallDir: 'C:/Tools/Fortify'

steps:
- task: PowerShell@2
  displayName: 'Download Fortify SCA'
  inputs:
    targetType: 'inline'
    script: |
      $output = "$(Agent.TempDirectory)\OpenText_SAST_Fortify_windows-x64_25.4.0.exe"
      Invoke-WebRequest -Uri "$(fortifyDownloadUrl)" -OutFile $output
- task: fortifyvsts-dev.hpe-security-fortify-vsts.build-task-fortify-sca-install.InstallFortifySCA@8
  inputs:
    version: '25.4.0'  # Specify the version of SCA you need
    InstallerPath: '$(Agent.TempDirectory)\OpenText_SAST_Fortify_windows-x64_25.4.0.exe'
    LicenseFile: '$(Agent.TempDirectory)\fortify.license'
    acceptEULA: true

# Optional: Add to PATH for next tasks
- script: |
    echo "##vso[task.prependpath]$(Agent.TempDirectory)/Fortify/bin"
  displayName: 'Add Fortify to PATH'